### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'keys'

### ISSUE THREAD

**Issue by EvilHomer0815** [derJD/python-mailcow#6]
mailcow alias get --all
Traceback (most recent call last):
  File "/home/phil/mailcowpython/bin/mailcow", line 8, in <module>
    sys.exit(main())
  File "/home/phil/mailcowpython/lib/python3.9/site-packages/mailcow/cli.py", line 78, in main
    tables = moo.as_table(vertical=args.vertical)
  File "/home/phil/mailcowpython/lib/python3.9/site-packages/mailcow/__init__.py", line 251, in as_table
    table.field_names = data.keys()
AttributeError: 'bytes' object has no attribute 'keys'

**Comment by Djiock** [comment]
Same issue for me...
